apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixelmind
  labels:
    app: pixelmind
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pixelmind
  template:
    metadata:
      labels:
        app: pixelmind
    spec:
      containers:
        - name: pixelmind
          image: shubhsemwal/pixelmind:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pixelmind-secrets
                  key: DATABASE_URL
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: pixelmind-secrets
                  key: AUTH_SECRET
            - name: HF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: pixelmind-secrets
                  key: HF_API_KEY
            - name: NEXTAUTH_URL
              valueFrom:
                secretKeyRef:
                  name: pixelmind-secrets
                  key: NEXTAUTH_URL
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: pixelmind-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: pixelmind-secrets
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: pixelmind-secrets
                  key: CLOUDINARY_API_SECRET
            - name: UPSTASH_REDIS_REST_URL
              valueFrom:
                secretKeyRef:
                  name: pixelmind-secrets
                  key: UPSTASH_REDIS_REST_URL
            - name: UPSTASH_REDIS_REST_TOKEN
              valueFrom:
                secretKeyRef:
                  name: pixelmind-secrets
                  key: UPSTASH_REDIS_REST_TOKEN
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /api/auth/session
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/auth/session
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
