apiVersion: v1
kind: Secret
metadata:
  name: pixelmind-secrets
type: Opaque
stringData:
  DATABASE_URL: "your-database-url"
  AUTH_SECRET: "your-auth-secret"
  HF_API_KEY: "your-hf-key"
  NEXTAUTH_URL: "http://pixelmind.local"
  CLOUDINARY_CLOUD_NAME: "your-cloud-name"
  CLOUDINARY_API_KEY: "your-api-key"
  CLOUDINARY_API_SECRET: "your-api-secret"
  UPSTASH_REDIS_REST_URL: "your-redis-url"
  UPSTASH_REDIS_REST_TOKEN: "your-redis-token"
