apiVersion: v1
kind: Secret
metadata:
  name: pixelmind-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:Semwal121094@db.hyyycabgthsvivcgindu.supabase.co:5432/postgres"
  AUTH_SECRET: "5a7b83ad9cded77b31b496d771c1fd44b0604a54d4de2e747d6d96d7b3c4b0ce"
  HF_API_KEY: <base64-value>
  NEXTAUTH_URL: "http://pixelmind.local"
  CLOUDINARY_CLOUD_NAME: "dmj6ur8sm"
  CLOUDINARY_API_KEY: "482573317125885"
  CLOUDINARY_API_SECRET: "N3VajhaCBcwjPEQTM_hKmEbYVSQ"
  UPSTASH_REDIS_REST_URL: "https://driving-gazelle-81871.upstash.io"
  UPSTASH_REDIS_REST_TOKEN: "gQAAAAAAAT_PAAIgcDI2ZjVkYzBlZWUxNDE0YWIwOGVjNzVmYmY2NWM0YWYzZA"
